## Numpy Library
Numpy is Numerical Python,A Fundamental Library for  Which is used of Scientific Computation in Python  
It Provides Support to vertor and Metrices along with a collection of Mathematical functions to operate with this Data Structure 

In [1]:
!pip install numpy


[notice] A new release of pip is available: 25.0.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip


In [6]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
print(type(arr))
arr.shape

<class 'numpy.ndarray'>


(6,)

In [9]:
arr.reshape(1,6)
print(type(arr))

<class 'numpy.ndarray'>


In [11]:
np.arange(0,10,2).reshape(5,1)


array([[0],
       [2],
       [4],
       [6],
       [8]])

In [14]:
# np.ones((3,4))
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [20]:
arr1=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr1)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [21]:
print("Array is :",arr1)
print("The Shape of Array",arr1.shape)
print("The Number of Dimentions",arr1.ndim)
print("Data Type",arr1.dtype)
print("Item In Size",arr1.itemsize)

Array is : [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
The Shape of Array (2, 5)
The Number of Dimentions 2
Data Type int64
Item In Size 8


In [29]:
arr=np.array([2,4,3,5,1,6])

print(np.sqrt(arr))
print(np.exp(arr))
print(np.log(arr))
print(np.sin(arr))

[1.41421356 2.         1.73205081 2.23606798 1.         2.44948974]
[  7.3890561   54.59815003  20.08553692 148.4131591    2.71828183
 403.42879349]
[0.69314718 1.38629436 1.09861229 1.60943791 0.         1.79175947]
[ 0.90929743 -0.7568025   0.14112001 -0.95892427  0.84147098 -0.2794155 ]


In [45]:
# accessing elements from array
print(arr[2]) ##One D array
print(arr1[0][2])
print(arr1[0:2,2:4])

3
3
[[3 4]
 [8 9]]


In [60]:
## Performing Statistics Operation
arr2=np.array([1,2,3,4,5,6,7,8])
mean=np.mean(arr2)
print("The Mean Is :",mean)
median=np.median(arr2)
print("The Median Is :",median)

# mode=np.mod(arr2)
# print("The Mode Is :",mode)
std_dev=np.std(arr2)
round_std=np.round(std_dev,2) ##round decimal to 2
print("The Standard Deviation is :",round_std)

normalized_data=(mean)/std_dev
print("The Normalized Data ",normalized_data)

## The Variance 
variance=np.var(arr2)
print("The Variance is ",variance)

arr2[(arr2>=5) & (arr2<=8)]

arr_min=np.min(arr2)
arr_max=np.max(arr2)
print(f"The Min is : {arr_min} The MAx is : {arr_max}")


reverse_ele=arr2[::-1]
print("The Reverse array",reverse_ele)

The Mean Is : 4.5
The Median Is : 4.5
The Standard Deviation is : 2.29
The Normalized Data  1.9639610121239315
The Variance is  5.25
The Min is : 1 The MAx is : 8
The Reverse array [8 7 6 5 4 3 2 1]
